### PR TITLE
Random things I have run into lately trying to use VF

### PR DESCRIPTION
**Pull request by fosterlynn**
Changed EconomicResource.quantity to currentQuantity.  
Changed AgentRelationship.context to scope.  
Added isFinished to Commitment.  
Added plannedStart and plannedDuration to Process in the ttl.  (Not an actual change, just a fix.)
Took off extraneous line in the UML, just a fix.

(If anyone disagrees with one of these, I'll remove it here and take it to a separate PR.)

### CODE REVIEW

**Comment by elf-pavlik** [comment]
> Added isFinished to Commitment.

Could you explain this one, how does it supposed to work with *vf:Fulfillment*?

**Comment by fosterlynn** [comment]
>>Added isFinished to Commitment.

>Could you explain this one, how does it supposed to work with vf:Fulfillment?

It assumes that the planned or estimated time could be wrong (often is wrong), so you can't go on that, but may need to close the commitment explicitly.  There also is often more than one event fulfilling a commitment, so you can't assume that because there is a fulfillment that is is complete.

**Comment by fosterlynn** [comment]
And one other thing I forgot to say - if one of the rdf experts could check on my use of xsd:boolean, that would be great.  (That is for isFinished.  And I had to add the @prefix up top too.)

**Comment by fosterlynn** [comment]
Also added link to github and welcom chat into the intro in the gitbook to resolve #254

**Comment by fosterlynn** [comment]
Also added link to github and welcom chat into the intro in the gitbook to resolve #254 

Removed isFinished from the ttl for now until resolved.  Merging to get the other stuff in.

**Pull request merged**
