### PR TITLE
interim name change to quantifiedAs

### PR DESCRIPTION
**Pull request by fosterlynn**
I'd like to do this while we continue to discuss it related to the scheduling milestone.  Seems better than what we have now in any case, and i'm not sure when we will finish hashing out the quantities.

### CODE REVIEW

**Comment by elf-pavlik** [comment]
could you please update examples as well?

**Comment by fosterlynn** [comment]
>could you please update examples as well?

done; and updated the times as well (oh maybe that was already done.... ah well, hopefully no yucky merge conflicts! if so, let me know, I'll fix ahead - was trying to not have to figure out rebase)

**Comment by elf-pavlik** [comment]
I included alternative version of fulfill-satisfy in #492 
If we can't resolve it in next couple of days I think we can rename examples with some suffixes like `-lq` and `-pq` to include both versions while we continue figuring things out.

**Comment by fosterlynn** [comment]
I'm closing this.  Had some push back on the name quantifiedAs, changed it to flowQuantity in the graphql reference for now until we can resolve quantity - or until next release of graphql spec basically.  And with all this time passed, there is no "interim".

**Pull request closed without merging**
