### PR TITLE
initial service examples

### PR DESCRIPTION
**Pull request by elf-pavlik**
First YAML examples inspired by those recent conversations:
* https://github.com/valueflows/valueflows/pull/391#issuecomment-451949728
* https://github.com/valueflows/vf-apps-traversing-the-flows/issues/4#issue-395979472
* https://github.com/valueflows/valueflows/issues/290#issuecomment-447584697
* #386 
* #392 
* #300

### CODE REVIEW

**Comment by elf-pavlik** [comment]
I may need to make a visual diagram for snippet in the last commit https://github.com/valueflows/valueflows/pull/393/commits/f6bd73357c4d7600b1cd071162dc68cbcbb43651

It should feed a lot into conversations happening in various issues and PRs

**Comment by elf-pavlik** [comment]
service

**Comment by elf-pavlik** [comment]
@fosterlynn I've added use of computing unit as input to processing faircoin transaction snippet

@sqykly from what I understand Holo currency will get exchanged for computing power, have you thought on how to represent those flows (economic events, commitments) which use computing power?

**Comment by fosterlynn** [comment]
I'm worried about the complexity of "included in" kinds of things on the operational level (as opposed to a summary level, which might be a different story). Seems like it messes with the simplicity of the base directed graph structure of the value flows.  I'll try an alternative treatment of this use case (and some other PRs that currently have this structure), to see if I can make it better or there are devils I haven't thought of.

**Comment by fosterlynn** [comment]
What are the definitions of actions "split" and "merge", and what do they replace?

**Comment by elf-pavlik** [comment]
> What are the definitions of actions "split" and "merge", and what do they replace?

Please think of them as plain *decrement* and *implement* which does not 'change existence'. I could have used *pop* and *push* instead.

**Comment by elf-pavlik** [comment]
I made a simple script for *track* from #391 and for diagram above when we start from *Alice's apples* it gives me correct: 

screenshot at 2019-01-10 18-53-14

It needs to keep track of visited nodes not to fall into looping over a cycle. I'll clean it up on Saturday and push a new repo to this organization. It does not rely on any specific serialization (JSON-LD, Trig, N-quads) and just builds on http://rdf.js.org/ interfaces.

Tree representation doesn't work that well since we have a graph, for now I'll just add a simple way to mark where nodes would start repeating. Above the last event in the bottom also goes as input to process on line 5.

**Comment by fosterlynn** [comment]
Here's a more elaborate treatment, which will be able to support inventory on the truck and lot numbers in a more specific way. ( "Merge" doesn't seem that good, because if Joe was going to use the fruit for anything that would go to others, he would keep them as separate resources to maintain the lot numbers coming from the growers.) 
delivery-service-2

**Comment by elf-pavlik** [comment]
In your last diagram:
* what quantity would you record as *unload*? just the quantity that Joe will take home? 
* can Jesus record work time for each of those small 4 processes related to specific operations on apples and pears?
* how would you see Jesus recording a distinct process for each 'processing of transaction with a consumer' which could have a work event specific to handling the whole transaction with a specific consumer? he may need that data for example to plan route based on statistics how long transactions with each of the consumers tend to last.

**Comment by fosterlynn** [comment]
>what quantity would you record as unload? just the quantity that Joe will take home?

yes

>can Jesus record work time for each of those small 4 processes related to specific operations on apples and pears?

if he wants -- not sure it would make sense for this use case since he is not splitting out his other inputs, but no problem with it, even if they are transfers imo

>how would you see Jesus recording a distinct process for each 'processing of transaction with a consumer' which could have a work event specific to handling the whole transaction with a specific consumer? he may need that data for example to plan route based on statistics how long transactions with each of the consumers tend to last.

that is included in the last version, no?

**Comment by elf-pavlik** [comment]
> that is included in the last version, no?

No you have two separate processes to split apples for Joe and split pears for Joe. I see a case where Jesus would want to record the whole transaction with Joe as one process which would involve splitting any number of resources and negotiating agreements based on available proposals. We can skip that negotiating agreements part for now and at least have one work event related to splitting both apples and pears for Joe, just as in my diagram for "Transaction with Joe" process.

**Comment by fosterlynn** [comment]
>No you have two separate processes to split apples for Joe and split pears for Joe

I suppose you could make one process, and rely on the tracking identifiers.  
deliver-joe

Better maybe to just log each separate delivery work event against the main process.

But, I think almost anything is better than adding the complication of nesting this type of process.

**Comment by fosterlynn** [comment]
>If we define vf:includedIn and vf:service as a way to nest flows and relate processes.

I don't think that we should define vf:includedIn, haven't seen a need for it yet.  We may find a need when we talk about non-operational higher-level processes, which is where it first came up.  But what I have seen so far operationally is that it adds more complexity than it is worth.

In terms of vf:service (as an action, right?) - I think it fits fine into the directed graph structure we have now without any nesting.  Should work very much like vf:produce, an output to a process whose inputs were used or consumed to create the service.  In the occasional cases where a service is created and is also input to the next process, then we talked about trying out using it as both an output and an input without the resource in between.  But that is still basically a flow, not a hierarchy, in terms of structure.

**Comment by fosterlynn** [comment]
>It looks like one of the approaches for #177 (comment) also to log more specific work events happening during longer work session.

Not quite sure of the implications to what you are considering, but our experience is that people often log a lot of work events for one commitment.  Sometimes this is logging every working session, which is convenient.  Or logging different pieces of the "task" so it is recorded separately for whatever reason (summary of workflow, communication of stages of the work, etc.).

But that doesn't mean that we need a summary work event for those.  As you point out, it is handled by the M:M between event and commitment.

**Comment by fosterlynn** [comment]
>If you prefer I could separate all the vf:includedIn occurrences into a separate PR based on discussions in #290 and #293

That might be helpful.  Or if there is one PR it is needed as part of, it can stay in that one.  

I'm thinking the examples are not a good place to introduce new things though?  Proposal: PRs for examples only include accepted vocabulary, or vocabulary that is defined in another PR where the spec is updated, instead of just examples.  OK with you?

**Comment by elf-pavlik** [comment]
> I'm thinking the examples are not a good place to introduce new things though?

I think we should never introduce new things if PR doesn't include examples. Possibly we can always start with examples and once we see consensus arising, then add missing terms and documentation to that PR.

**Comment by fosterlynn** [comment]
>I think we should never introduce new things if PR doesn't include examples.

This also seems like a good idea.  But changes need explanation, at least a definition. So let's figure out how to do both in PRs?

**Comment by fosterlynn** [comment]
Closing after v.3, please re-open if we re-look at this topic.

**Pull request closed without merging**
