### PR TITLE
initial transportation use case snippets

### PR DESCRIPTION
**Pull request by elf-pavlik**
Initial examples for https://github.com/valueflows/valueflows/wiki/Use-Cases-and-Requirements#transportation

* some variants similar to other variants have differences explained in comment blocks.
* load & unload for packaged and serial variants affect the same (transported) resource just in two different places
* snippets introduce *assemble* and *disassemble* actions as reversible variants of *consume* and *produce*

### TODO

* [x] variant of transporting non serial resource where transportation includes *load* from different resources with the same classification and *unload* to different resources with the same classification, while still allows to *tie together* matching *load* & *unload*. Similar to what current `vf:Transfer` does but without having anything to do with *rights and responsibilities*.

### CODE REVIEW

**Comment by elf-pavlik** [comment]
Last commits adds a concurrent transportation example addressing *TODO* in issue description. It tries to reuse process nesting #293 to connect *load* and *unload* pairs in non ambiguous way.

**Comment by elf-pavlik** [comment]
Latest commit adds snippet which involves passenger transportation. It works a little bit like package, and in this case *split* and *merge* sound little weird :package:

**Comment by elf-pavlik** [comment]
#393 includes scenario which shows some limitations with *load* and *unload* - lack of 'on the vehicle' resource which we can get affected by various events.

**Comment by fosterlynn** [comment]
Closing after v.3, please re-open if we re-look at this topic.

**Pull request closed without merging**
