### PR TITLE
add @elioqoshi's logo

### PR DESCRIPTION
**Pull request by ahdinosaur**
ref: https://github.com/valueflows/valueflows/issues/38

### CODE REVIEW

**Comment by ahdinosaur** [comment]
@elioqoshi: check it out: <https://valueflo.ws>. :)

now that you've contributed to Value Flows, feel free to add yourself to [AUTHORS](https://github.com/valueflows/valueflows/blob/master/AUTHORS). (click that link, then click :pencil2:, then add your name and email, then save with a commit message (anything really), then submit pull request. or send me name and email and i'm happy to do it)

**Comment by elioqoshi** [comment]
@ahdinosaur Great! Done :)

**Comment by elioqoshi** [comment]
valueflows github-01

Can we add the logo also to the Organization profile here on GitHub?

**Comment by fosterlynn** [comment]
>Can we add the logo also to the Organization profile here on GitHub?

@elioqoshi Yes please!  (If not already done...)

**Comment by elioqoshi** [comment]
@fosterlynn you should be able to do that (or add me to the organization) :)

**Comment by bhaugen** [comment]
@elioqoshi - we tried, github says you are already a member.

**Comment by elioqoshi** [comment]
Right, only owners can change the profile photo. So you might be able to do that @bhaugen

**Comment by bhaugen** [comment]
I tried with the beautiful svg image, but github won't take it. Must be png or jpg. Got a preferred version of one of those? I'd hate to degrade the design by some sloppy conversion.

**Comment by fosterlynn** [comment]
done, i think

**Comment by elioqoshi** [comment]
Perfect!

**Comment by ahdinosaur** [comment]
:cake:

**Pull request merged**
