### PR TITLE
added intended qty

### PR DESCRIPTION
**Pull request by fosterlynn**
define better later (we have been looking at several different quantities in Intents)

### CODE REVIEW

**Comment by elf-pavlik** [comment]
Since we have `affects` and `affectedQuantity` for `EconomicEvent`, and we have `involves` for `Commitment` and `Intent` we could have matching `involvedQuantity` for both `Commitment` and `Intent`

**Comment by fosterlynn** [comment]
How about this?  

observedQuantity: this applies to all actions, and is the quantity that will be accounted for (then when we do time-based resources, we can add whatever is appropriate, and differentiate in whatever different ways we need to - but the observedQuantity will be always counted when things get summarized - whether there is an inventoried resource or not - makes more sense than affectedQuantity, which implies only that which affects resources

committedQuantity: also makes more sense than involvedQuantity, which isn't even a good descriptive word in the first place - what we need to know is what the person committed to (in NRP for example when a person commits to some work, they can change the originally intended time estimate to what they estimate - also applies to all actions

IntendedQuantity: just following the pattern, again I don't think involvedQuantity is accurate, since nothing is involved at the moment - and we can define later as needed, but we know we need some quantity as part of the intention

I think this would be a great piece of cleanup, and doesn't preclude other quantities and durations also used when we get to those use cases.

**Comment by elf-pavlik** [comment]
Please go ahead with your proposal as long as all those properties stay *unstable*. Which means we leave it open to go back to `vf:affectedQuantity` and add just `vf:involvedQuantity`.
Actually we might even go with `affectedClassifiedAs` and `involvedClassifiedAs` to keep it all consistent with what describes the flow and what describes *affected* or *involved* resource.
We should also clarify if we need different properties or can just have same one for any flow. I can't recall why we currently have distinct ones for Intent, Commitment and Flow.
 
> and is the quantity that will be accounted for (then when we do time-based resources, we can add whatever is appropriate, and differentiate in whatever different ways we need to - but the observedQuantity will be always counted when things get summarized

I don't think we can decide anything like that at this moment. Luckily we have *schedules* milestone coming up next which should give us chance to clarify it all further. Once again, we may reverse this change based on this upcoming work.

**Comment by fosterlynn** [comment]
>We should also clarify if we need different properties or can just have same one for any flow. I can't recall why we currently have distinct ones for Intent, Commitment and Flow.

That is a good question.  I think we ended up with involves because we started with affected, and affected didn't work as well for commitments.  I could be fine with just one.

**Comment by fosterlynn** [comment]
OK, went with proposal, see what you think.

**Comment by elf-pavlik** [comment]
I think we still miss property to use with Commitment

**Comment by fosterlynn** [comment]
>I think we still miss property to use with Commitment

right above intendedQuantity (committedQuantity)

**Pull request merged**
