### PR TITLE
snapshot of the essepunto spec, otherwise working only intermittently

### PR DESCRIPTION
**Pull request by fosterlynn**
@elf-pavlik help? I can't remember how to test this in gitbook (works directly from my local drive) - but I think there is a way to do that.  I'm thinking we'll need to take snapshots by just saving in the browser when we add things.  And see if it is stays up more than it is down.

Ref. https://github.com/valueflows/valueflows/issues/493 which I will close and just leave this open.

### CODE REVIEW

**Comment by elf-pavlik** [comment]
I would prefer not to add such manual step which will complicate all PR changing the turtle file. Let's better look at changing to something else dynamic.

**Comment by fosterlynn** [comment]
>I would prefer not to add such manual step which will complicate all PR changing the turtle file. Let's better look at changing to something else dynamic.

Well, I would prefer that too, of course, just takes research.  Don't see anything from a cursory search.  Will look more later.

**Comment by fosterlynn** [comment]
Update: on the essepuntato github, says they are looking for other server space, don't know when or if it will be back. https://github.com/essepuntato/LODE/issues/21.  It talks about the web version, I'll check to see if there is something that can be used locally to create a snapshot, understanding that is not the best option.

Also, did a search, doesn't look super promising, but there are some tools listed here https://www.w3.org/2011/prov/wiki/Generating_HTML_documentation_of_OWL.

Another option is to investigating generating doc from the graphql reference, or a json-schema reference (which I'll get to at some point).

**Comment by fosterlynn** [comment]
Resolved.

**Pull request closed without merging**
