### PR TITLE
hotel example with checkin-checkout

### PR DESCRIPTION
**Pull request by fosterlynn**
First example, transfer without transportation, with scheduling.

I think I'll also try an alternative example using a service.

Went back to using the different quantity names for I-C-E.  Not sure we can find one name that will communicate well.

### CODE REVIEW

**Comment by fosterlynn** [comment]
Added an alternative example using service (hotel stay).  One issue: no event for checking in, since the service is one package.

**Comment by elf-pavlik** [comment]
Thanks @fosterlynn 

How do you see situation where Alice and Hotel enter an agreement
* Hotel provides to Alice room availability for specific time interval
* Alice provides to Hotel whatever

Later Alice ends up checking in a day after her reservation started, and checking out a day before it ends. They may still want to follow the initial agreement which has the duration of reservation / availability and not the duration of actual use. Hotel still have delivered the full agreed duration of availability even if Alice for whatever reason only actually used some smaller duration.

I think we need to give more focus to `Satisfaction` and `Fulfillment`. I will write now snippet to more https://fairbnb.coop/ like scenario when person rents just one specific flat on very specific schedule. So Intents involving that flat represent a very specific schedule (plan) this person would like to provide its availability to someone else. Later agreed Commitments represent a very specific reservation (shared plans). The final Events can get recorded but agreements will rely just on reservations / availability and as long as provider respected them, actual *use* of the flat will not get taken into consideration of fulfilling commitments. Maybe just people who *use* that flat can use them for some 'efficiency' evaluations.

**Comment by elf-pavlik** [comment]
FairBnB style bungalow which sometimes gets rented out:

```yaml
'@context':
  - https://git.io/vf-examples-jsonld-context
  - bnb: https://bnb.example/
    alice: https://alice.example/
    bob: https://bob.example/

'@graph':

  - '@id': bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c9
    '@type': EconomicResource
    skos:note: charming bungalow near center of Amatlan
    classifiedAs: wd:Q850107
    currentQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
```

Intents allow to represent intended schedule (independent plan) to make it available to rent

```yaml
  - '@id': bnb:ba3c5350-e2e5-4e94-b971-84b1cd8ac236
    '@type': Intent
    skos:note: first renting period in Q1
    action: reserve
    provider: https://bnb.example/
    involves: bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c9
    involvesQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    hasBegining: 2019-01-06T00:00:00-5:00
    hasEnd: 2019-02-19T00:00:00-5:00
    
  - '@id': bnb:2f7bd443-2323-4039-9a52-b999288edbeb
    '@type': Intent
    skos:note: second renting period in Q1
    action: reserve
    provider: https://bnb.example/
    involves: bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c9
    involvesQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    hasBegining: 2019-02-27T00:00:00-5:00
    hasEnd: 2019-03-31T00:00:00-5:00
```

We could represent it with this diagram

bnb-intents

Commitments allow to represent agreed reservations (shared plans)

```yaml
- '@id': bnb:b9726077-f7ac-4f05-87b3-54f89bdf2826
    '@type': Commitment
    skos:note: Alice's reservation
    action: reserve
    provider: https://bnb.example/
    receiver: https://alice.example/
    involves: bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c9
    involvesQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    hasBegining: 2019-02-03T00:00:00-5:00
    hasEnd: 2019-02-11T00:00:00-5:00
    
  - '@id': bnb:7a9ad680-70eb-4743-97bf-26f1c56d52a8
    '@type': Commitment
    skos:note: Bob's reservation
    action: reserve
    provider: https://bnb.example/
    receiver: https://alice.exapmle/
    involves: bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c9
    involvesQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    hasBegining: 2019-03-12T00:00:00-5:00
    hasEnd: 2019-03-17T00:00:00-5:00
```
We can also add them to the diagram:

bnb-commitments

Agreement between BnB and Alice as well as BnB and Bob get made based on time on reservation. This way even if person renting bungalow arrives late and leaves early it doesn't affect the agreement. If they want to arrive earlier than agreed or leave later, they have to renegotiate agreement and BnB would do it based on other existing reservations.

**Comment by fosterlynn** [comment]
>action: reserve

What do you do with the event? Actions need to be the same.

>Agreement between BnB and Alice as well as BnB and Bob get made based on time on reservation.

How do you account for this in the agreement?  What is the unit of the quantity implied in the duration?  (What if someone rents for a month?)  How would you add the other side of the agreement (the pays whatever)?

**Comment by elf-pavlik** [comment]
>  What is the unit of the quantity implied in the duration?

I think SI has *second* as base unit of time. 
I also don't understand where you see something implied. All the flows (both Intents and Commitments) have explicit beginning and end.

> How would you add the other side of the agreement (the pays whatever)?

I don't see where we would have any complication in agreement itself, it just relies on very specific Commitments. We still need to look how to construct Agreement Templates #266 which allow to create Agreements in similar way ProcessRecipe allows to create Process.

> What do you do with the event? Actions need to be the same.

I think as soon as the committed interval starts and as agreed bungalow stays available to recipient, we can start observing fulfillment of promised reservation. I see its only difference from *use* that one doesn't have to actually use it just to keep it *reserved*.

**Comment by elf-pavlik** [comment]
Example of observing *reserve* event on restaurant table:

reserved table

Still no one eating at (*use*) the table

**Comment by fosterlynn** [comment]
>> What is the unit of the quantity implied in the duration?

>I think SI has _second_ as base unit of time.
>I also don't understand where you see something implied. All the flows (both Intents and Commitments) have explicit beginning and end.

But what if second is not a good unit of measure for the situation?  For example the hotel or bnb probably charges by the day (or week or month), and the day is not 24 hours or however many seconds because of checkin and checkout times and time to clean the room in between.  Not sure when second would be useful really - to make it useful you would have to convert it and apply rules to it.

>> How would you add the other side of the agreement (the pays whatever)?

>I don't see where we would have any complication in agreement itself, it just relies on very specific Commitments.

What I meant was, how would you construct the commitments?  You don't want to pay be the second.

I don't see why to force fit this, why not leave it direct and simple?  Why not have a 'reasonable' quantity, with a 'normal' quantity construct of number and unit of measure, and also record the time duration for purposes of coordination and scheduling?

**Comment by fosterlynn** [comment]
An alternative treatment of the bnb example without `reserve`.  Using intent as you did (although alternatively, bnb could also block off times with Commitments of their own, which I think would be simpler in terms of processing).  More work to do on intents, as we know, so this is just an approximation.

```yaml
'@context':
  - https://git.io/vf-examples-jsonld-context
  - bnb: https://bnb.example/
    alice: https://alice.example/
    bob: https://bob.example/

'@graph':

  - '@id': bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c9
    '@type': EconomicResource
    skos:note: charming bungalow near center of Amatlan
    classifiedAs: wd:Q850107
    currentQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    unitOfAvailability: unit:Night # or something like that


# Intents allow to represent intended schedule (independent plan) to make it available to rent

  - '@id': bnb:ba3c5350-e2e5-4e94-b971-84b1cd8ac236
    '@type': Intent
    skos:note: first renting period in Q1
    action: give
    provider: https://bnb.example/
    involves: bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c9
    availableQuantity:
      qudt:unit: unit:Night
      qudt:numericValue: 13
    hasBegining: 2019-01-06T00:00:00-5:00
    hasEnd: 2019-02-19T00:00:00-5:00
    
  - '@id': bnb:2f7bd443-2323-4039-9a52-b999288edbeb
    '@type': Intent
    skos:note: second renting period in Q1
    action: give
    provider: https://bnb.example/
    involves: bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c9
    availableQuantity:
      qudt:unit: unit:Night
      qudt:numericValue: 31
    hasBegining: 2019-02-27T00:00:00-5:00
    hasEnd: 2019-03-31T00:00:00-5:00

- '@id': bnb:b9726077-f7ac-4f05-87b3-54f89bdf2826
    '@type': Commitment
    skos:note: Alice's reservation
    action: give
    provider: https://bnb.example/
    receiver: https://alice.example/
    involves: bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c9
    committedQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    committedTime: 2019-02-03T00:00:00-5:00

- '@id': bnb:b9726077-f7ac-4f05-87b3-54f89bdf2825
    '@type': Commitment
    skos:note: Alice's reservation
    action: give
    provider: https://alice.example/
    receiver: https://bnb.example/
    involves: bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c9
    involvesQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    committedTime: 2019-02-11T00:00:00-5:00
    
  - '@id': bnb:7a9ad680-70eb-4743-97bf-26f1c56d52a8
    '@type': Commitment
    skos:note: Bob's reservation
    action: give
    provider: https://bnb.example/
    receiver: https://bob.exapmle/
    involves: bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c9
    involvesQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    committedTime: 2019-03-12T00:00:00-5:00
    hasEnd: 2019-03-17T00:00:00-5:00
    
  - '@id': bnb:7a9ad680-70eb-4743-97bf-26f1c56d52a7
    '@type': Commitment
    skos:note: Bob's reservation
    action: give
    provider: https://bob.example/
    receiver: https://bnb.exapmle/
    involves: bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c9
    involvesQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    committedTime: 2019-03-17T00:00:00-5:00
```

**Comment by fosterlynn** [comment]
Calendar processing: This one would probably be by Night.  Here's one from airbnb, wrong dates for this example of course. But generally, color coding for availability etc.
bnb-calendar

Off the top of my head:
``` 
for each day in the month:
    if is in intent:
        if last commitment is to give:
            show as unavailable
        else
            show as available
```

Or I'm sure there are better ways to do it, and would need more nuance.

**Comment by elf-pavlik** [comment]
Can you please add version where Alice has intent to book a bungalow on specific dates for 10 days. After CfA BnB creates two commitments which partially satisfy this commitment
* first 2 days - bungalow 3
* remaining 8 days - bungalow 8 (which Alice prefers but someone else had booked for the first two days)

This way we'll have 2 partial Satisfactions - first one for first 2 days out of 10 days interval, second for remaining 8 days out of 10 days interval.

Later we can do it for more general ouikit example, where besides time interval we also have > 1 number of items.

**Comment by fosterlynn** [comment]
>Can you please add version where Alice has intent to book a bungalow on specific dates for 10 days. After CfA BnB creates two commitments which partially satisfy this commitment
>   * first 2 days - bungalow 3
>    * remaining 8 days - bungalow 8 (which Alice prefers but someone else had booked for the first two days)

I think I actually might like this kind of rental as a service better, with the bungalow as an input to the process that produces the service, but there will be iss.

```yaml
'@context':
  - https://git.io/vf-examples-jsonld-context
  - bnb: https://bnb.example/
    alice: https://alice.example/

'@graph':

  - '@id': bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c9
    '@type': EconomicResource
    name: bungalow 3
    skos:note: charming bungalow near center of Amatlan 
    classifiedAs: wd:Q850107
    currentQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1

  - '@id': bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c8
    '@type': EconomicResource
    name: bungalow 8
    skos:note: charming bungalow near center of Amatlan
    classifiedAs: wd:Q850107
    currentQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1

# Intents allow to represent intended schedule (independent plan) to make it available to rent

  - '@id': bnb:ba3c5350-e2e5-4e94-b971-84b1cd8ac236
    '@type': Intent
    skos:note: bungalow 3 availability
    action: checkin
    provider: https://bnb.example/
    involves: bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c9 # bungalow 3
    intendedQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    hasBegining: 2019-01-06T00:00:00-5:00
    hasEnd: 2019-02-19T00:00:00-5:00

  - '@id': bnb:ba3c5350-e2e5-4e94-b971-84b1cd8ac244
    '@type': Intent
    skos:note: bungalow 3 availability
    action: checkout
    receiver: https://bnb.example/
    involves: bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c9 # bungalow 3
    intendedQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    hasBegining: 2019-01-06T00:00:00-5:00
    hasEnd: 2019-02-19T00:00:00-5:00
    
  - '@id': bnb:2f7bd443-2323-4039-9a52-b999288edbea
    '@type': Intent
    skos:note: bungalow 8 availability
    action: checkin
    provider: https://bnb.example/
    involves: bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c8 # bungalow 8
    intendedQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    hasBegining: 2019-02-20T00:00:00-5:00
    hasEnd: 2019-03-31T00:00:00-5:00
   
  - '@id': alice:2f7bd443-2323-4039-9a52-b999288edbex # part of one proposal
    '@type': Intent
    action: checkin
    receiver: https://alice.example/
    resourceClassifiedAs: wd:Q850107
    intendedQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    intendedTime: 2019-02-17T00:00:00-5:00
   
  - '@id': alice:2f7bd443-2323-4039-9a52-b999288edbec # part of same proposal
    '@type': Intent
    action: checkout
    provider: https://alice.example/
    resourceClassifiedAs: wd:Q850107
    intendedQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    intendedTime: 2019-02-27T00:00:00-5:00

    # commitments after cfa

- '@id': bnb:b9726077-f7ac-4f05-87b3-54f89bdf2826
    '@type': Commitment
    skos:note: Alice's reservation for bungalow 3
    action: checkin
    provider: https://bnb.example/
    receiver: https://alice.example/
    involves: bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c9
    committedQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    committedTime: 2019-02-17T00:00:00-5:00

  - '@id': bnb:b52a5815-fae9-43bf-be95-833b95dc0ada
    '@type': Satisfaction
    satisfies: alice:2f7bd443-2323-4039-9a52-b999288edbex # alice's intent
    satisfiedBy: bnb:b9726077-f7ac-4f05-87b3-54f89bdf28264 # the commitment
    satisfiedQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1

  - '@id': bnb:b52a5815-fae9-43bf-be95-833b95dc0adh
    '@type': Satisfaction
    satisfies: bnb:ba3c5350-e2e5-4e94-b971-84b1cd8ac236 # the bnb's intent
    satisfiedBy: bnb:b9726077-f7ac-4f05-87b3-54f89bdf28264 # the commitment
    satisfiedQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1

- '@id': bnb:b9726077-f7ac-4f05-87b3-54f89bdf2824
    '@type': Commitment
    skos:note: Alice's reservation for bungalow 3
    action: checkout
    provider: https://alice.example/
    receiver: https://bnb.example/
    involves: bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c9
    involvesQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    committedTime: 2019-02-19T00:00:00-5:00

  - '@id': bnb:b52a5815-fae9-43bf-be95-833b95dc0ad0
    '@type': Satisfaction
    satisfies: alice:2f7bd443-2323-4039-9a52-b999288edbec # alice's intent
    satisfiedBy: bnb:b9726077-f7ac-4f05-87b3-54f89bdf2824 # the commitment
    satisfiedQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1

  - '@id': bnb:b52a5815-fae9-43bf-be95-833b95dc0ad9
    '@type': Satisfaction
    satisfies: bnb:ba3c5350-e2e5-4e94-b971-84b1cd8ac244 # the bnb's intent
    satisfiedBy: bnb:b9726077-f7ac-4f05-87b3-54f89bdf2824 # the commitment
    satisfiedQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1

# etc. for the bungalow 8 .....
```

**Comment by elf-pavlik** [comment]
I see Satisfaction here only reflects the 'resource amount' but doesn't capture the duration dimension. I'll jump into writing YAML which will first tackle the simple case here with 'resource amount' constant 1 and various duration. Later testing it with more general 'ouikit' case which has both duration and 'resource amount' varying.

**Comment by elf-pavlik** [comment]
```yaml
'@context':
  - https://git.io/vf-examples-jsonld-context
  - bnb: https://bnb.example/
    alice: https://alice.example/
    bob: https://bob.example/

'@graph':

  # BnB's resources

  - '@id': bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c9
    '@type': EconomicResource
    skos:note: Bungalow 3
    classifiedAs: wd:Q850107
    currentQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1

  - '@id': bnb:c5fdb509-bba0-4907-ad7c-cc5012c5852d
    '@type': EconomicResource
    skos:note: Bungalow 8
    classifiedAs: wd:Q850107
    currentQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1

  # BnB's intents (independent plan)

  - '@id': bnb:ba3c5350-e2e5-4e94-b971-84b1cd8ac236
    '@type': Intent
    skos:note: first renting period in Q1 - B3 for 44 days
    action: reserve
    provider: https://bnb.example/
    involves: bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c9
    involvesQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    hasBegining: 2019-01-06T00:00:00-5:00
    hasEnd: 2019-02-19T00:00:00-5:00
    
  - '@id': bnb:2f7bd443-2323-4039-9a52-b999288edbeb
    '@type': Intent
    skos:note: second renting period in Q1 - B3 for 32 days
    action: reserve
    provider: https://bnb.example/
    involves: bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c9
    involvesQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    hasBegining: 2019-02-27T00:00:00-5:00
    hasEnd: 2019-03-31T00:00:00-5:00

  - '@id': bnb:66e28e22-3a95-44a2-836d-3fe4cd77e4ae
    '@type': Intent
    skos:note: first renting period in Q1 - B8 for 44 days
    action: reserve
    provider: https://bnb.example/
    involves: bnb:c5fdb509-bba0-4907-ad7c-cc5012c5852d
    involvesQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    hasBegining: 2019-01-06T00:00:00-5:00
    hasEnd: 2019-02-19T00:00:00-5:00
    
  - '@id': bnb:acbd8df2-134f-4418-afe2-ef19197de131
    '@type': Intent
    skos:note: second renting period in Q1 - B8 for 32 days
    action: reserve
    provider: https://bnb.example/
    involves: bnb:c5fdb509-bba0-4907-ad7c-cc5012c5852d
    involvesQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    hasBegining: 2019-02-27T00:00:00-5:00
    hasEnd: 2019-03-31T00:00:00-5:00

  # Alice's intents (independnet plan)

  - '@id': alice:a4ac54d0-63b7-460d-b1e6-96352c1a567d
    '@type': Intent
    skos:note: reserving bungalow for 8 days
    action: reserve
    receiver: https://alice.example/
    resourceClassifiedAs: wd:Q850107
    involvesQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    hasBegining: 2019-02-03T00:00:00-5:00
    hasEnd: 2019-02-11T00:00:00-5:00

  # Bob's intents (independent plan)

  - '@id': bob:19d57544-3561-4401-adec-e84d95ec8cf0
    '@type': Intent
    skos:note: reserving bungalow for 13 days
    action: reserve
    receiver: https://alice.exapmle/
    resourceClassifiedAs: wd:Q850107
    involvesQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    hasBegining: 2019-01-23T00:00:00-5:00
    hasEnd: 2019-02-06T00:00:00-5:00


  # BnB's commitments to Bob (shared plan) + satisfactions

  - '@id': bnb:7a9ad680-70eb-4743-97bf-26f1c56d52a8
    '@type': Commitment
    skos:note: Bob's reservation for b8 - 13 days
    action: reserve
    provider: https://bnb.example/
    receiver: https://alice.exapmle/
    involves: bnb:c5fdb509-bba0-4907-ad7c-cc5012c5852d
    involvesQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    hasBegining: 2019-01-23T00:00:00-5:00
    hasEnd: 2019-02-06T00:00:00-5:00

  - '@id': bnb:1754ffa3-33e4-4c5c-b681-185a45b0e69b
    '@type': Satisfaction
    satisfies: bnb:66e28e22-3a95-44a2-836d-3fe4cd77e4ae
    satisfiedBy: bnb:7a9ad680-70eb-4743-97bf-26f1c56d52a8
    satisfiedQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    satisfiedInterval:
      hasBegining: 2019-01-23T00:00:00-5:00
      hasEnd: 2019-02-06T00:00:00-5:00

  - '@id': bob:c7a561b1-0452-444f-bbca-d4babd2adbe0
    '@type': Satisfaction
    satisfies: bob:19d57544-3561-4401-adec-e84d95ec8cf0
    satisfiedBy: bnb:7a9ad680-70eb-4743-97bf-26f1c56d52a8
    satisfiedQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    satisfiedInterval:
      hasBegining: 2019-01-23T00:00:00-5:00
      hasEnd: 2019-02-06T00:00:00-5:00

  # BnB's commitments to Alice (shared plan) + satisfactions
    
  - '@id': bnb:b9726077-f7ac-4f05-87b3-54f89bdf2826
    '@type': Commitment
    skos:note: Alice's reservation for b3 - 3 days
    action: reserve
    provider: https://bnb.example/
    receiver: https://alice.example/
    involves: bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c9
    involvesQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    hasBegining: 2019-02-03T00:00:00-5:00
    hasEnd: 2019-02-06T00:00:00-5:00

  - '@id': bnb:b9726077-f7ac-4f05-87b3-54f89bdf2826
    '@type': Commitment
    skos:note: Alice's reservation for b8 - 5 days
    action: reserve
    provider: https://bnb.example/
    receiver: https://alice.example/
    involves: bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c9
    involvesQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    hasBegining: 2019-02-06T00:00:00-5:00
    hasEnd: 2019-02-11T00:00:00-5:00

  - '@id': bnb:a5bcd4c3-80b1-49dd-8931-f9c3d79feecb
    '@type': Satisfaction
    satisfies: bnb:ba3c5350-e2e5-4e94-b971-84b1cd8ac236
    satisfiedBy: bnb:b9726077-f7ac-4f05-87b3-54f89bdf2826
    satisfiedQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    satisfiedInterval:
      hasBegining: 2019-02-03T00:00:00-5:00
      hasEnd: 2019-02-06T00:00:00-5:00

  - '@id': alice:7095860c-1774-472e-99a9-01096017fa6b
    '@type': Satisfaction
    satisfies: alice:a4ac54d0-63b7-460d-b1e6-96352c1a567d
    satisfiedBy: bnb:b9726077-f7ac-4f05-87b3-54f89bdf2826
    satisfiedQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    satisfiedInterval:
      hasBegining: 2019-02-03T00:00:00-5:00
      hasEnd: 2019-02-06T00:00:00-5:00

  - '@id': bnb:b53d4687-e430-4227-bcc1-eb9b7bdbde17
    '@type': Satisfaction
    satisfies: bnb:66e28e22-3a95-44a2-836d-3fe4cd77e4ae
    satisfiedBy: bnb:b9726077-f7ac-4f05-87b3-54f89bdf2826
    satisfiedQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    satisfiedInterval:
      hasBegining: 2019-02-06T00:00:00-5:00
      hasEnd: 2019-02-11T00:00:00-5:00

  - '@id': alice:3da2033a-17e5-4f75-bca5-00bef112f242
    '@type': Satisfaction
    satisfies: alice:a4ac54d0-63b7-460d-b1e6-96352c1a567d
    satisfiedBy: bnb:b9726077-f7ac-4f05-87b3-54f89bdf2826
    satisfiedQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    satisfiedInterval:
      hasBegining: 2019-02-06T00:00:00-5:00
      hasEnd: 2019-02-11T00:00:00-5:00
```

**Comment by elf-pavlik** [comment]
Case where one commitment satisfies two intents (but not the matching ones)

```yaml

  # Claus' intents (independnet plan)

  - '@id': claus:d2a3e85d-47f4-4034-982f-2e694a9dd1ac
    '@type': Intent
    skos:note: reserving bungalow for first weekend of march
    action: reserve
    receiver: https://claus.example/
    resourceClassifiedAs: wd:Q850107
    involvesQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    hasBeginning: 2019-02-28T00:00:00-5:00
    hasEnd: 2019-03-03T00:00:00-5:00

  - '@id': claus:f266747d-a022-4f3b-9e8b-c8c215305ee4
    '@type': Intent
    skos:note: reserving bungalow for second weekend of march
    action: reserve
    receiver: https://claus.example/
    resourceClassifiedAs: wd:Q850107
    involvesQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    hasBeginning: 2019-03-07T00:00:00-5:00
    hasEnd: 2019-03-10T00:00:00-5:00

  # BnB's commitments to Claus (shared plan) + satisfactions
    
  - '@id': bnb:7f74b0fe-c387-4926-a041-3c1b0475104e
    '@type': Commitment
    skos:note: Claus' reservation for b3 - 10 days
    action: reserve
    provider: https://bnb.example/
    receiver: https://claus.example/
    involves: bnb:70ee3034-0d15-4471-8ee3-91c60bb1a9c9
    involvesQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    hasBeginning: 2019-02-28T00:00:00-5:00
    hasEnd: 2019-03-10T00:00:00-5:00

  - '@id': bnb:a3d7258a-df2a-4bfa-9cf3-d86d90d6cc34
    '@type': Satisfaction
    satisfies: bnb:2f7bd443-2323-4039-9a52-b999288edbeb
    satisfiedBy: bnb:7f74b0fe-c387-4926-a041-3c1b0475104e
    satisfiedQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    satisfiedInterval:
      hasBeginning: 2019-02-06T00:00:00-5:00
      hasEnd: 2019-02-11T00:00:00-5:00

  - '@id': claus:106239db-48fc-490a-8355-b7a1bafe1877
    '@type': Satisfaction
    satisfies: claus:d2a3e85d-47f4-4034-982f-2e694a9dd1ac
    satisfiedBy: bnb:7f74b0fe-c387-4926-a041-3c1b0475104e
    satisfiedQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    satisfiedInterval:
      hasBeginning: 2019-02-28T00:00:00-5:00
      hasEnd: 2019-03-03T00:00:00-5:00

  - '@id': claus:71726d6b-5ee0-40f4-a922-b7070d832f01
    '@type': Satisfaction
    satisfies: claus:f266747d-a022-4f3b-9e8b-c8c215305ee4
    satisfiedBy: bnb:7f74b0fe-c387-4926-a041-3c1b0475104e
    satisfiedQuantity:
      qudt:unit: unit:Number
      qudt:numericValue: 1
    satisfiedInterval:
      hasBeginning: 2019-03-07T00:00:00-5:00
      hasEnd: 2019-03-10T00:00:00-5:00

```

**Pull request closed without merging**
