### PR TITLE
Add Algorithms section

### PR DESCRIPTION
**Pull request by bhaugen**
I think this will render ok, but don't know how to see the rendered contents locally, and don't have any experience writing for gitbooks. Feel free to reject if anybody sees anything wrong.

(I do think the contents will be useful, though.)

### CODE REVIEW

**Comment by bhaugen** [comment]
I'm closing this pull request after a chat with @elf-pavlik and moving the algorithm section into the appendix.

**Comment by elf-pavlik** [comment]
You don't have to close pull request, you can just add more commits to it

**Comment by bhaugen** [comment]
Thanks, I did not know that. But I'll wait until Lynn comes back to redo the PR.

**Comment by bhaugen** [comment]
Moved to appendices

**Comment by bhaugen** [comment]
will make new PR

**Comment by bhaugen** [comment]
I'm trying to get this merged. Lost in github PR mazes....

**Pull request merged**
